name: test_env_xarrayutils
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray < 0.15
  - dask
  - numpy
  - black
  - astropy
  - matplotlib
  # Necesary additions for the plotting tools (might have to make thos optional)
  - gsw
  - cftime # !!! omit in one once the tests are optional
  - cartopy
  - xgcm
  - scipy
  - pip
  - pip:
    - codecov
    - pytest-cov
